services:
  api:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - REPAIR_NINJA_MODE=PROD
      - REPAIR_NINJA_DB_ENGINE=django.db.backends.mysql
      - REPAIR_NINJA_DB_HOST=db
      - REPAIR_NINJA_DB_PORT=3306
      - REPAIR_NINJA_DB_NAME=${DB_NAME}
      - REPAIR_NINJA_DB_USER=${DB_USER}
      - REPAIR_NINJA_DB_PASSWORD=${DB_PASSWORD}
      - REPAIR_NINJA_DJANGO_SECRET_KEY=${SECRET_KEY}
      - REPAIR_NINJA_ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - REPAIR_NINJA_CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - REPAIR_NINJA_SMTP=${THIRD_PARTY_SMTP:-0}
      - REPAIR_NINJA_EMAIL_HOST=${EMAIL_HOST:-127.0.0.1}
      - REPAIR_NINJA_EMAIL_PORT=${EMAIL_PORT:-25}
      - REPAIR_NINJA_EMAIL_USE_TLS=${EMAIL_USE_TLS:-1}
      - REPAIR_NINJA_EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - REPAIR_NINJA_EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - REPAIR_NINJA_DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-webmaster@localhost}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.3.0
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 5s
      timeout: 5s
      retries: 5

  proxy:
    build:
      context: ./docker/proxy
    restart: always
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - static-data:/vol/web
      - proxy-dhparams-data:/vol/proxy
      - certbot-certs-data:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}

  certbot:
    build:
      context: ./docker/certbot
    command: echo "Run certbot manually..."
    environment:
      - EMAIL=${ACME_DEFAULT_EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - static-data:/vol/web
      - certbot-certs-data:/etc/letsencrypt
    depends_on:
      - proxy

volumes:
  mysql-data:
  static-data:
  proxy-dhparams-data:
  certbot-certs-data: